version: "3.8"
services:
  chirpbot:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./docker/nginx/localhost.key:/etc/nginx/localhost.key
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mysql:
    image: mysql:5.7
    restart: always