version: "3.7"
services:
  mysql:
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: chirpbot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
  chirpbot:
    ports:
      - '8080:8080'